name: traffic_sim
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State management
  provider: ^6.1.5
  
  # Network
  http: ^1.4.0
  connectivity_plus: ^6.1.4
  
  # UI
  fl_chart: ^1.0.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  
  # File operations
  path_provider: ^2.1.5
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf